version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  labels:
  - BUMP depencency
  ignore:
  - dependency-name: react-query
    versions:
    - "> 3.8.3, < 4"
  - dependency-name: "@sentry/integrations"
    versions:
    - 6.3.1
    - 6.3.3
  - dependency-name: "@types/node"
    versions:
    - 14.14.34
    - 15.0.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.23
  - dependency-name: "@types/react"
    versions:
    - 17.0.4
  - dependency-name: jest-watch-typeahead
    versions:
    - 0.6.3
  - dependency-name: react-use
    versions:
    - 17.2.4
  - dependency-name: "@sentry/browser"
    versions:
    - 6.0.3
    - 6.0.4
    - 6.2.0
    - 6.2.3
    - 6.3.1
  - dependency-name: eslint-config-prettier
    versions:
    - 8.3.0
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.23.0
    - 7.25.0
  - dependency-name: react-hook-form
    versions:
    - 7.0.0
    - 7.2.0
    - 7.2.1
    - 7.3.4
  - dependency-name: "@sentry/node"
    versions:
    - 6.0.3
    - 6.3.1
  - dependency-name: "@material-ui/core"
    versions:
    - 5.0.0-alpha.31
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.12.0
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.16
    - 13.1.4
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.1.1
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.4
