stages:
 - build
 #- push_to_ecr
 #- deploy

.sandbox_triggers: &sandbox_triggers
  refs:
    - sandbox

.prod_triggers: &prod_triggers
  refs:
    - master

build-sandbox:
  stage: build
  tags:
    - front
  script:
    - rm -rf src/tools &&  cd src
    - git clone git@gitlab.tooling-sapien.network:group-tools/tools.git
    #- git submodule init   &&  git submodule update --remote
    - cd ..
    ##- git pull --recurse-submodule
    - export KUBECONFIG=~/.kube/kubeconfig_sapien-sandbox-cluster
    - export AWS_PROFILE=sapien-sandbox
    - export AWS_REGION=us-east-2
    ### service env vars
    - export NODE_ENV=local
    - export LOG_LEVEL=debug
    - export PORT="4000"
    - envsubst < .env-temp > .env
    - pwd

    ### login to ecr
    - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 994750220687.dkr.ecr.us-east-2.amazonaws.com
    - docker build -t front-v3:latest .
    - docker tag front-v3:latest 994750220687.dkr.ecr.us-east-2.amazonaws.com/front-v3:latest
    - docker push 994750220687.dkr.ecr.us-east-2.amazonaws.com/front-v3:latest
    - cd eks-manif &&  envsubst <  front-dep-temp.yml > front-dep.yml
    - cat front-dep.yml
    - kubectl delete -f  front-dep.yml && kubectl apply -f front-dep.yml
  only:
    <<: *sandbox_triggers

build-deploy-prod:
  stage: build
  tags:
    - back-main
  script:
    - echo "prod deployment goes here"
  only:
    <<: *prod_triggers