stages:
 - build
 - cleanupImages
 #- push_to_ecr
 #- deploy

variables:
  # this variable can be overriden by pipeline run variable
  ENV: "sandbox"

.sandbox_triggers: &sandbox_triggers
  refs:
    - sandbox

.qat_triggers: &qat_triggers
  refs:
    - qat

.poc_triggers: &poc_triggers
  refs:
    - poc


build-sandbox:
  stage: build
  tags:
    - front
  script:
    - rm -rf tools
    - git clone http://$USER:$CI_TOKEN@gitlab.tooling-sapien.network/group-tools/tools.git
    #- git submodule init   &&  git submodule update --remote
    #- cd ..
    ##- git pull --recurse-submodule
    - export KUBECONFIG=~/.kube/kubeconfig_sapien-sandbox-cluster
    - export AWS_PROFILE=sapien-sandbox
    - export AWS_REGION=us-east-2
    ### service env vars
    - export ENV=SANDBOX
    - export NODE_ENV=SANDBOX
    - export S3_BUCKET_NAME_SANDBOX=sapien-sandbox
    - envsubst < .env.example > .env
    ### login to ecr
    - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 994750220687.dkr.ecr.us-east-2.amazonaws.com
    - docker build -t front-v3:$CI_COMMIT_SHORT_SHA .
    - docker tag front-v3:$CI_COMMIT_SHORT_SHA 994750220687.dkr.ecr.us-east-2.amazonaws.com/front-v3:$CI_COMMIT_SHORT_SHA
    - docker push 994750220687.dkr.ecr.us-east-2.amazonaws.com/front-v3:$CI_COMMIT_SHORT_SHA
    - export ENV=sandbox
    - cd eks-manif &&  envsubst <  front-dep-temp.yml > front-dep.yml
    - cat front-dep.yml
    - kubectl apply -f front-dep.yml
  environment:
    name: sandbox
    url: https://front-sandbox.sapien.network
  
  only:
    <<: *sandbox_triggers

cleanup-sandbox:
  stage: cleanupImages
  tags:
    - front-sandbox
  script:
    - docker images | awk '{print $3}' | xargs -l docker rmi -f
  when: manual
  only:
    <<: *sandbox_triggers  

build-qat:
  stage: build
  tags:
    - front-qat
  script:
    - rm -rf tools
    - git clone http://$USER:$CI_TOKEN@gitlab.tooling-sapien.network/group-tools/tools.git
    #- git submodule sync && git submodule update
    - export KUBECONFIG=~/.kube/kubeconfig_sapien-qat-cluster
    - export AWS_PROFILE=sapien-qat
    - export AWS_REGION=us-east-2
    - export ENV=QAT
    - export S3_BUCKET_NAME_QAT=sapien-qat
    - export NODE_ENV=QAT
    - export LOG_LEVEL=debug
    - envsubst < .env.example > .env
    ### login to ecr
    - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 081984521558.dkr.ecr.us-east-2.amazonaws.com
    - docker build -t front-v3:$CI_COMMIT_SHORT_SHA .
    - docker tag front-v3:$CI_COMMIT_SHORT_SHA 081984521558.dkr.ecr.us-east-2.amazonaws.com/front-v3:$CI_COMMIT_SHORT_SHA
    - docker push 081984521558.dkr.ecr.us-east-2.amazonaws.com/front-v3:$CI_COMMIT_SHORT_SHA
    - export ENV=qat
    - cd eks-manif &&  envsubst <  front-dep-temp-q.yml > front-dep.yml
    - cat front-dep.yml
    - kubectl apply -f front-dep.yml
  environment:
    name: qat
    url: https://front-qat.sapien.network  
  only:
    <<: *qat_triggers

cleanup-qat:
  stage: cleanupImages
  tags:
    - front-qat
  script:
    - docker images | awk '{print $3}' | xargs -l docker rmi -f
  when: manual
  only:
    <<: *qat_triggers  


build-poc:
  stage: build
  tags:
    - front-poc
  script:
    - rm -rf tools
    - git clone http://$USER:$CI_TOKEN@gitlab.tooling-sapien.network/group-tools/tools.git
    #- git submodule init   &&  git submodule update --remote
    #- cd ..
    ##- git pull --recurse-submodule
    - export KUBECONFIG=~/.kube/kubeconfig_sapien-poc-cluster
    - export AWS_PROFILE=sapien-poc
    - export AWS_REGION=us-east-2
    - export ENV=POC
    - export S3_BUCKET_NAME_POC=sapien-poc
    - export NODE_ENV=POC
    - export LOG_LEVEL=debug
    - envsubst < .env.example > .env
    ### login to ecr
    - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 081984521558.dkr.ecr.us-east-2.amazonaws.com
    - docker build -t front-v3:$CI_COMMIT_SHORT_SHA .
    - docker tag front-v3:$CI_COMMIT_SHORT_SHA 081984521558.dkr.ecr.us-east-2.amazonaws.com/front-v3:$CI_COMMIT_SHORT_SHA
    - docker push 081984521558.dkr.ecr.us-east-2.amazonaws.com/front-v3:$CI_COMMIT_SHORT_SHA
    - export ENV=poc
    - cd eks-manif &&  envsubst <  front-dep-temp-prd.yml > front-dep.yml
    - cat front-dep.yml
    - kubectl apply -f front-dep.yml
  environment:
    name: poc
    url: https://front-poc.sapien.network  
  only:
    <<: *poc_triggers

cleanup-poc:
  stage: cleanupImages
  tags:
    - front-poc
  script:
    - docker images | awk '{print $3}' | xargs -l docker rmi -f
  when: manual
  only:
    <<: *poc_triggers   
