name: CI

on:
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  validate:
    name: 'Linting & Test'
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Current Builds
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 15.5.0

      - name: Install
        run: npm ci --only=production

      - name: Lint
        run: npm run lint
      - name: Tests
        run: npm run test:coverage
