name: CI

on:
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  validate:
    name: 'Lint & Test'
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Current Builds
        if: ${{ !env.ACT }}
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{secrets.GIT_PAT}}

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 15.5.0

      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            .jest-cache
            .eslintcache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Tests
        run: npm run test:coverage
